blog/urls.py
from .views import *
from django.urls import path

app_name='app_blog'
urlpatterns = [
    path('', blog_mostrar_todos, name="blog_mostrar_todos"),
    path('blog_detalle/<id>', blog_mostrar_detalle, name="blog_mostrar_detalle"),
    path('blog_update/<id>', blog_update, name="blog_update"),
    path('blog_crear', blog_nuevo, name="blog_crear"),
    path('blog_editar/<id>', blog_update, name="blog_editar"),
    path('blog_comentar/<id>', blog_comentar, name="blog_comentar"),
    path('blog_eliminar/<id>', blog_eliminar, name="blog_eliminar"),
]

entrega_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuario.views import *
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuario.urls', namespace= 'app_user')),
    path('blog/', include('blog.urls', namespace= 'app_blog')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from .views import *
from django.urls import path
from django.conf.urls.static import static

app_name='app_user'
urlpatterns = [
    path('', inicio, name="usuario_inicio"),
    path('register', user_register, name="user_register"),
    path('user_login', user_login, name="user_login"),
    path("user_logout/", LogoutView.as_view(next_page='app_user:usuario_inicio'), name="user_logout"),
    path('user_perfil/<int:user_id>/', user_perfil, name='user_perfil'),
    path("user_editar_perfil/", user_perfil_editar, name='user_editar_perfil'),
    path("user_borrar_perfil/", user_perfil_borrar, name='user_borrar_perfil'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=100)
    cuerpo = models.TextField()
    fecha = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.titulo} - {self.autor}'
    
class Comentario(models.Model):
    autor=models.ForeignKey(User, on_delete=models.CASCADE)
    receptor=models.ForeignKey(Blog, on_delete=models.CASCADE)
    cuerpo = models.TextField()
    def __str__(self):
        return f'comentario de {self.autor} en {self.receptor}'

blog/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
import datetime


class Blog_create_form(ModelForm):
    imagen=forms.ImageField(required=True)
    field_order=['titulo', 'subtitulo', 'cuerpo', 'imagen']
    class Meta:
        model = Blog
        fields = {'titulo', 'subtitulo', 'cuerpo', 'imagen'}

class Blog_comentar_form(ModelForm):
    cuerpo=forms.CharField(label='comentar')
    class Meta:
        model = Comentario
        fields = {'cuerpo'}

blog/views.py
from typing import Any, Dict
from .models import *
from .forms import * 
from usuario.models import Perfil
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.template import Template, Context, loader
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import path
import datetime

# Create your views here.
@login_required
def blog_nuevo(request):
    if request.method=='POST':
        form=Blog_create_form(request.POST, request.FILES)
        if form.is_valid():
            blog=form.save(commit=False)
            blog.autor=request.user
            blog.save()
            return render (request, 'blog_listar.html', {'formulario':form, 'perfil':conseguir_perfil(request)})
        else:
            mensaje='datos invalidos'
            return render (request, 'blog_crear.html', {'formulario':form,'mensaje':mensaje, 'perfil':conseguir_perfil(request)})
    else:
        form=Blog_create_form()
        return render (request, 'blog_crear.html', {'formulario':form, 'perfil':conseguir_perfil(request)})

def blog_mostrar_detalle(request, id):
    
    blog=Blog.objects.get(id=id)
    comentarios=comentarios_leer(request,id)
    form=Blog_comentar_form()
    return render (request, 'post.html', {'blog':blog, 'comentarios':comentarios, 'formulario':form, 'perfil':conseguir_perfil(request)})
    # mostrar el blog en los template --listo--
    pass

def blog_mostrar_todos(request):
    
    lista_blog=Blog.objects.all()
    return render (request, 'blog_listar.html', {'lista_blog':lista_blog, 'perfil':conseguir_perfil(request)})
    # Mostrar cada blog en un FOR en los template --listo--

@login_required
def blog_update(request, id):
    blog=get_object_or_404(Blog, id=id)
    # es importante que el unico que pueda editar sea el autor y el admin  --listo--
    if request.user == blog.autor or request.user.is_staff:
        if request.method=='POST':
            form=Blog_create_form(request.POST, request.FILES, instance=blog)
            if form.is_valid():
                form.save()
                return render (request, 'blog_listar.html', {'formulario':form, 'blog':blog, 'perfil':conseguir_perfil(request)})
            else:
                mensaje='datos invalidos'
                return render (request, 'blog_editar.html', {'formulario':form,'mensaje':mensaje, 'blog':blog, 'perfil':conseguir_perfil(request)})
        else:
            form=Blog_create_form(instance=blog)
            return render (request, 'blog_editar.html', {'formulario':form, 'blog':blog, 'perfil':conseguir_perfil(request)})
    else:
        return redirect('app_blog:blog_mostrar_todos')

@login_required
def blog_eliminar(request, id):
    blog=get_object_or_404(Blog, id=id)
    if request.user == blog.autor or request.user.is_staff:
        if request.method=='POST':
            blog.delete()
            return redirect('app_blog:blog_mostrar_todos')
        else:
            return render(request, 'blog_eliminar.html', {'blog':blog, 'perfil':conseguir_perfil(request)})
    else:
        return HttpResponseForbidden("No tienes permiso para editar este blog.")
            
    pass


def comentarios_leer(request, id):
    receptor=Blog.objects.get(id=id)
    comentarios=Comentario.objects.filter(receptor=receptor)
    return comentarios

@login_required
def blog_comentar(request, id):
    if request.method=='POST':
        form=Blog_comentar_form(request.POST)
        if form.is_valid():
            comentario=form.save(commit=False)
            comentario.autor=request.user
            receptor=Blog.objects.get(id=id)
            comentario.receptor=receptor
            comentario.save()
            return redirect('app_blog:blog_mostrar_detalle', id=id)
        else:
            return redirect('app_blog:blog_mostrar_detalle', id=id)
    else:
        return redirect('app_blog:blog_mostrar_todos')
    

def conseguir_perfil(request):
    if request.user.is_authenticated:
        perfil, created = Perfil.objects.get_or_create(user=request.user)
        if created==True:
            perfil.imagen = '/media/avatares/default_avatar.png' 
            perfil.save()             
        return perfil

blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog_crear.html
{% extends "index.html" %}

{% load static %}

{% block encabezado %} Blog {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block blog %}

<form action="{% url 'app_blog:blog_crear' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <input type="submit" value="Ingresar">
</form>



{% endblock %}

blog/templates/blog_editar.html
{% extends "index.html" %}

{% load static %}

{% block encabezado %} Blog {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block blog %}

<form action="{% url 'app_blog:blog_editar' blog.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <input type="submit" value="Ingresar">
</form>



{% endblock %}

blog/templates/blog_eliminar.html
{% extends "index.html" %}

{% load static %}

{% block encabezado %} Blog {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block blog %}

<form action="{% url 'app_blog:blog_eliminar' blog.id %}" method="POST" >{% csrf_token %}
    <h4>Desea borrar el Blog???</h4>
    <input type="submit" value="SI">
</form>

{% endblock %}

blog/templates/blog_listar.html
{% extends "index.html" %}

{% load static %}

{% block encabezado %} Blog {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block blog %}

{% for blog in lista_blog %}
<!-- Post preview-->
    <div class="post-preview">
        <a href="{% url 'app_blog:blog_mostrar_detalle' blog.id %}">
            <h2 class="post-title">{{ blog.titulo }}</h2>
            <h3 class="post-subtitle">{{ blog.subtitulo }}</h3>
        </a>
        <p class="post-meta">
            Autor: 
            <a href="{% url 'app_user:user_perfil' blog.autor.id %}">{{ blog.autor }}</a>
            {{ blog.fecha }}
        </p>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
    {% endfor %}
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'app_blog:blog_crear' %}">crear nuevo blog</a>
    {% endif %}


{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block encabezado %} {% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet"/>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" style="color: black;" href="{% url 'app_user:usuario_inicio' %}">inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        {% if perfil.imagen %}
                        <img src= '{{ user.perfil.imagen.url }}' alt="Avatar" style="width:50px;height:50px;">
                        {% endif %}
                        {% if user.is_authenticated %}
                        <p style="color: black;">{{ user.username }}</p>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_perfil' user_id=request.user.id %}">Mi perfil</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_logout' %}">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_register' %}">registrar</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('/static/blog/assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{% block titulo %} {% endblock %}</h1>
                            <span class="subheading">{% block subtitulo %} {% endblock %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% block blog %} {% endblock %}
                    <!-- Pager-->
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>


<!-- Post preview
<div class="post-preview">
    <a href="post.html">
        <h2 class="post-title">Failure is not an option</h2>
        <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to future generations.</h3>
    </a>
    <p class="post-meta">
        Posted by
        <a href="#!">Start Bootstrap</a>
        on July 8, 2023
    </p>
</div>
 Divider
<hr class="my-4" />
Pager-->

blog/templates/post.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet"/>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" style="color: black;" href="{% url 'app_user:usuario_inicio' %}">inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        {% if perfil.imagen %}
                        <img src= '{{ perfil.imagen.url }}' alt="Avatar" style="width:50px;height:50px;">
                        {% endif %}
                        <p style="color: black;">{{ user.username }}</p>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_perfil' user_id=request.user.id %}">Mi perfil</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_logout' %}">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_register' %}">registrar</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{ blog.imagen.url }}')"> <!-- aca esta la imagen-->
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ blog.titulo }}</h1> <!-- titulo-->
                            <h2 class="subheading">{{ blog.subtitulo }}</h2> <!-- subtitulo-->
                            <span class="meta">
                                Autor:
                                <a href="{% url 'app_user:user_perfil' blog.autor.id %}">{{ blog.autor }}</a> <!-- Autor--><!-- blog.autor-->
                                {{ blog.fecha }} <!-- Fecha-->
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{ blog.cuerpo }}</p> <!-- Cuerpo-->
                    </div>
                </div>
            </div>
        </article>
        {% if request.user == blog.autor or request.user.is_staff %}
        <a class="btn btn-primary" href="{% url 'app_blog:blog_editar' blog.id %}">editar blog</a>
        <a class="btn btn-primary" href="{% url 'app_blog:blog_eliminar' blog.id %}">Eliminar blog</a>
        {% endif %}
        
        <!-- comentarios -->
        {% for comentario in comentarios %}
            <p><b>{{ comentario.autor }}: </b>{{ comentario.cuerpo }}</p>
        {% endfor %}

        <!-- comentar-->
        <form action="{% url 'app_blog:blog_comentar' blog.id %}" method="POST" >{% csrf_token %}
            <table>
                {{ formulario.as_table }}
            </table>
            <input type="submit" value="Comentar">
        </form>
        
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>