blog/urls.py
from .views import *
from django.urls import path

app_name='app_blog'
urlpatterns = [
    path('', blog_mostrar_todos, name="blog_mostrar_todos"),
    path('blog_detalle/<id>', blog_mostrar_detalle, name="blog_mostrar_detalle"),
    path('blog_update/<id>', blog_update, name="blog_update"),
    path('blog_crear', blog_nuevo, name="blog_crear"),
    path('blog_editar/<id>', blog_update, name="blog_editar"),
    path('blog_comentar/<id>', blog_comentar, name="blog_comentar"),
    path('blog_eliminar/<id>', blog_eliminar, name="blog_eliminar"),
]

entrega_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuario.views import *
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuario.urls', namespace= 'app_user')),
    path('blog/', include('blog.urls', namespace= 'app_blog')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from .views import *
from django.urls import path
from django.conf.urls.static import static

app_name='app_user'
urlpatterns = [
    path('', inicio, name="usuario_inicio"),
    path('register', user_register, name="user_register"),
    path('user_login', user_login, name="user_login"),
    path("user_logout/", LogoutView.as_view(next_page='app_user:usuario_inicio'), name="user_logout"),
    path('user_perfil/<int:user_id>/', user_perfil, name='user_perfil'),
    path("user_editar_perfil/", user_perfil_editar, name='user_editar_perfil'),
    path("user_borrar_perfil/", user_perfil_borrar, name='user_borrar_perfil'),
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Perfil(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='avatares', null=True, blank=True)
    descripcion=models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return f"perfil de {self.user}"

usuario/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class User_register_form(UserCreationForm):
    first_name=first_name=forms.CharField(label='Nombre')
    email=forms.EmailField(label='Email usuario')
    password1=forms.CharField(label='contraseña', widget=forms.PasswordInput)
    password2=forms.CharField(label='confirmar contraseña', widget=forms.PasswordInput)
    field_order=['username','first_name', 'email', 'password1', 'password2']
    class Meta:
        model = User
        fields={'username', 'first_name', 'email', 'password1', 'password2'}
        help_texts= { k:'' for k in fields }

class User_perfil_form(ModelForm): # ModelForm fue la solucion a todos mis problemas
    #descripcion=forms.CharField(required=False, widget=forms.Textarea)
    #imagen=forms.ImageField(label='imagen')
    field_order=['descripcion', 'imagen']
    class Meta:
        model = Perfil
        fields = {'descripcion', 'imagen'}
    
class User_edit_form(UserCreationForm):
    first_name=forms.CharField(label='Nombre')
    email=forms.EmailField(label='Email')
    password1=forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)
    field_order=['first_name', 'email', "password1", 'password2']
    class Meta:
        model = User
        #fields={'username', 'email', 'first_name', 'password1', 'password2'}
        fields={'email', 'first_name', 'password1', 'password2'}
        #help_texts= { k:'' for k in fields }

usuario/views.py
from typing import Any, Dict
from .models import *
from .forms import * 
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.template import Template, Context, loader
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import path

# Create your views here.
def inicio(request):
    return render(request, "inicio.html")

def user_register (request):
    if request.method=="POST":
        form=User_register_form(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usu=info['username']
            form.save()                    
            mensaje=f'usuario "{usu}" creado correctamente'
            return render(request, "user_register.html", {'formulario':form, 'mensaje':mensaje})
        else:
            mensaje='datos invalidos'
            return render(request, "user_register.html", {'formulario':form, 'mensaje':mensaje})
    else:
        form = User_register_form()
        mensaje=""
        return render(request, "user_register.html", {'formulario':form, 'mensaje':mensaje})
    pass

def user_login(request):
    if request.method=='POST':
        form=AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usu=info['username']
            clave=info['password']
            usuario=authenticate(username=usu, password=clave)
            if usuario != None:
                login(request, usuario)
                mensaje=f'usuario "{usu}" logueado correctamente'
                return render(request, "inicio.html", {'formulario':form, 'mensaje':mensaje})
        else:
            mensaje='datos invalidos'
            return render(request, "user_login.html", {'formulario':form, 'mensaje':mensaje})
    else:
        form=AuthenticationForm()
        mensaje=''
        return render(request, "user_login.html", {'formulario':form, 'mensaje':mensaje})

def user_perfil(request, user_id=None): #muestra mi perfil o muestra un perfil un perfil pedido
    if user_id is None:
        user = request.user
    else:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return redirect('app_blog:blog_mostrar_todos')    
    perfil, created = Perfil.objects.get_or_create(user=user)
    if created==True:
        perfil.imagen = '/media/avatares/default_avatar.png' 
        perfil.save()    
    return render(request, 'user_perfil.html', {'perfil': perfil})


@login_required
def user_perfil_editar(request): #No entra nunca en el if form.is_valid///pd. si no estoy logueado se rompe todo
    usuario=request.user
    perfil=Perfil.objects.get(user=usuario)
    # if request.user.is_staff or perfil.user==request.user: HACE FALTA ESTO??
    if request.method=='POST':
        form_user=User_edit_form(request.POST, instance=usuario)
        form_perfil=User_perfil_form(request.POST, request.FILES, instance=perfil)
        if form_perfil.is_valid() and form_user.is_valid(): #posiblemente el problema este aca
            form_user.save()
            form_perfil.save()
            usuario=authenticate(
                username=request.user.username,
                password=form_user.cleaned_data['password1'])      
            if usuario is not None:
                login(request, usuario)

            return render (request, 'user_perfil.html', {'form_user':form_user, 'form_perfil':form_perfil, 'perfil':perfil})
        else:
            mensaje='Datos invalidos'
            return render(request, 'user_edit_perfil.html', {'form_user':form_user, 'form_perfil':form_perfil,'mensaje': mensaje}) 
    else:
        form_user=User_edit_form(instance=perfil.user)
        # form_perfil=User_perfil_form(instance=perfil)
        form_perfil=User_perfil_form(initial={'imagen':perfil.imagen, 'descripcion':perfil.descripcion}) #con el instance chillaba asi que decidi no renegar
        return render (request, 'user_edit_perfil.html', {'form_user':form_user, 'form_perfil':form_perfil,  'perfil':perfil})
    

            # info_perfil=form_perfil.cleaned_data
            # info_user=form_user.cleaned_data
            # perfil.user=usuario
            # usuario.first_name=info_user['first_name'] # lo guarda
            # usuario.email=info_user['email'] # lo guarda
            # usuario.password1=info_user['password1'] # lo guarda
            # usuario.password2=info_user['password2'] # lo guarda
            # perfil.descripcion=info_perfil['descripcion'] #lo guarda
            # imagen=request.FILES['imagen']
            # perfil.imagen=imagen #al fin lo guarda, era un tema en el template
            # avatar_viejo=Perfil.objects.filter(user=usuario)
            # if len(avatar_viejo)>0:
            #     avatar_viejo=avatar_viejo[0].imagen
            #     avatar_viejo.delete()


@login_required
def user_perfil_borrar(request):
    perfil=get_object_or_404(Perfil, user=request.user)
    if request.user == perfil.user or request.user.is_staff:
        if request.method=='POST':
            perfil.delete()
            return redirect('app_user:usuario_inicio')
        else:
            return render(request, 'perfil_eliminar.html', { 'perfil':perfil})
    else:
        return HttpResponseForbidden("No tienes permiso para editar este blog.")
    pass

usuario/templates/inicio.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} inicio {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block contenido %}
    <h3 style="color: white;"> Acerca de mi:</h3>
    <p style="color: white;"><b>Tomas Di Renzo</b></p>
    <p style="color: white;"><b>Tengo 24 años y vivo en buenos aires </b></p>
    <p style="color: white;"><b>Email: direnzotomas@gmail.com</b></p>
    <p style="color: white;"><b>haciendo un breve curso de python logre hacer esta pagina, <br> no es la gran cosa pero es mia y la arme desce cero </b>{{perfil.descripcion}}</p>

{% endblock %}

usuario/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block encabezado %} {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" style="color: black;" href="{% url 'app_user:usuario_inicio' %}">inicio</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        {% if perfil %}
                        <img src= '{{ user.perfil.imagen.url }}' alt="Avatar" style="width:50px;height:50px;">
                        {% endif %}
                        {% if user.is_authenticated %}
                        <p style="color: black;">{{ user.username }}</p>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_perfil' user_id=request.user.id %}">Mi perfil</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_logout' %}">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_register' %}">registrar</a></li>
                        <li class="nav-item"><a class="nav-link" style="color: black;" href="{% url 'app_user:user_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white-75 mb-5 font-weight-bold">{% block titulo %} Titulo {% endblock %}</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">{% block subtitulo %} {% endblock %}</p>
                        <a class="btn btn-primary btn-xl" href="{% url 'app_blog:blog_mostrar_todos' %}">Blog</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        {% block contenido %} {% endblock %}
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        

usuario/templates/perfil_eliminar.html
{% extends "index.html" %}

{% load static %}

{% block encabezado %} Blog {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block blog %}

<form action="{% url 'app_user:user_borrar_perfil' %}" method="POST" >{% csrf_token %}
    <h4>Desea borrar el Perfil???</h4>
    <input type="submit" value="SI">
</form>

{% endblock %}

usuario/templates/user_borrar_perfil.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} inicio {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block contenido %}

<h4>{{ mensaje }}</h4>

<h4>Desea borrar su perfil????</h4>

<a class="btn btn-warning" href="{% url 'app_user:user_borrar_perfil' %}" method="POST">SI</a>
<a class="btn btn-danger" href="{% url 'app_user:user_perfil' %}">NO</a>

{% endblock %}

usuario/templates/user_edit_perfil.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} inicio {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block contenido %}

<h4>{{ mensaje1 }}</h4>
<h4>{{ mensaje2 }}</h4>

<form action="{% url 'app_user:user_editar_perfil' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <!-- Estuve un dia entero peleandome con esto por no poner el enctype --> 
    <table>
        {{ form_perfil.as_table }}
        {{ form_user.as_table }}
    </table>
    <input type="submit" value="Ingresar">
</form>

{% endblock %}

usuario/templates/user_login.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} inicio {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block contenido %}

<h4>{{ mensaje }}</h4>

<form action="{% url 'app_user:user_login' %}" method="POST">{% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <input type="submit" value="Ingresar">
</form>

{% endblock %}

usuario/templates/user_perfil.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} Perfil de {{perfil.user.username}} {% endblock %}

{% block titulo %} Perfil de {{perfil.user.username}} {% endblock %}

{% block subtitulo %} Este es el perfil de {{perfil.user.username}} {% endblock %}

{% block contenido %}

    <img src= '{{ perfil.imagen.url }}' alt="Avatar" style="width:200px;height:200px;"> 
    <br>
    <br>
    <p style="color: white;"><b>Usuario: </b>{{perfil.user.username}}</p>
    <p style="color: white;"><b>Nombre: </b>{{perfil.user.first_name}}</p>
    <p style="color: white;"><b>Email: </b>{{perfil.user.email}}</p>
    <p style="color: white;"><b>descripcion: </b>{{perfil.descripcion}}</p>
    {% if request.user == perfil.user or request.user.is_staff %}
    <a class="btn btn-warning" href="{% url 'app_user:user_editar_perfil' %}">editar perfil</a>
    <a class="btn btn-danger" href="{% url 'app_user:user_borrar_perfil' %}">borrar perfil</a>
    {% endif %}


{% endblock %}

usuario/templates/user_register.html
{% extends "padre.html" %}

{% load static %}

{% block encabezado %} inicio {% endblock %}

{% block titulo %} Bienvenidos a mi blog de comida {% endblock %}

{% block subtitulo %} este es un blog de cocina {% endblock %}

{% block contenido %}

<h4>{{ mensaje }}</h4>

<form action="{% url 'user_register' %}" method="POST">{% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <input type="submit" value="Ingresar">
</form>

{% endblock %}